# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# PLEASE DO NOT EDIT THIS FILE DIRECTLY - it is auto-generated
class Structoptimizer < Formula
  desc "Go struct alignment optimization tool"
  homepage "https://github.com/gamelife1314/structoptimizer"
  url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.0/structoptimizer-linux-amd64.tar.gz"
  sha256 "PLACEHOLDER_LINUX_AMD64_SHA256"
  version "1.8.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.0/structoptimizer-darwin-amd64.tar.gz"
      sha256 "PLACEHOLDER_DARWIN_AMD64_SHA256"
    end
    on_arm do
      url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.0/structoptimizer-darwin-arm64.tar.gz"
      sha256 "PLACEHOLDER_DARWIN_ARM64_SHA256"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.0/structoptimizer-linux-amd64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_AMD64_SHA256"
    end
    on_arm do
      url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.0/structoptimizer-linux-arm64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_ARM64_SHA256"
    end
  end

  def install
    bin.install "structoptimizer"
  end

  test do
    system "#{bin}/structoptimizer", "-version"
  end
end
