# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# PLEASE DO NOT EDIT THIS FILE DIRECTLY - it is auto-generated
class Structoptimizer < Formula
  desc "Go struct alignment optimization tool"
  homepage "https://github.com/gamelife1314/structoptimizer"
  url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.2/structoptimizer-linux-amd64.tar.gz"
  sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
  version "1.8.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.2/structoptimizer-darwin-amd64.tar.gz"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    end
    on_arm do
      url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.2/structoptimizer-darwin-arm64.tar.gz"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.2/structoptimizer-linux-amd64.tar.gz"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    end
    on_arm do
      url "https://github.com/gamelife1314/structoptimizer/releases/download/v1.8.2/structoptimizer-linux-arm64.tar.gz"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    end
  end

  def install
    bin.install "structoptimizer"
  end

  test do
    system "#{bin}/structoptimizer", "-version"
  end
end
