package reporter

import (
	"fmt"
	"strings"
	"time"

	"github.com/gamelife1314/structoptimizer/optimizer"
)

// GenerateMD 生成 Markdown 格式报告
func (r *Reporter) GenerateMD(report *optimizer.Report) (string, error) {
	var sb strings.Builder

	sb.WriteString("# 🚀 StructOptimizer 优化报告\n\n")
	sb.WriteString(fmt.Sprintf("> 🕐 生成时间：%s  \n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("> 📦 版本：v%s\n\n", Version))

	// 1. 优化总览
	sb.WriteString("## 📊 优化总览\n\n")
	sb.WriteString("| 指标 | 数值 |\n")
	sb.WriteString("|------|------|\n")
	sb.WriteString(fmt.Sprintf("| 🔹 处理结构体总数 | **%d** |\n", report.TotalStructs))
	sb.WriteString(fmt.Sprintf("| ✅ 优化的结构体 | **%d** |\n", report.OptimizedCount))
	sb.WriteString(fmt.Sprintf("| ⏭️ 跳过的结构体 | **%d** |\n", report.SkippedCount))
	if report.TotalSaved > 0 {
		sb.WriteString(fmt.Sprintf("| 💾 节省内存 | **%d 字节** (%.2f KB) |\n",
			report.TotalSaved, float64(report.TotalSaved)/1024))
	} else {
		sb.WriteString("| 💾 节省内存 | 0 字节 |\n")
	}
	if report.RootStruct != "" {
		sb.WriteString(fmt.Sprintf("| 🎯 主结构体 | `%s` |\n", report.RootStruct))
		if report.RootStructSize > 0 {
			optRate := float64(report.RootStructSize-report.RootStructOptSize) / float64(report.RootStructSize) * 100
			sb.WriteString(fmt.Sprintf("| 📏 优化前大小 | **%d 字节** |\n", report.RootStructSize))
			sb.WriteString(fmt.Sprintf("| 📏 优化后大小 | **%d 字节** |\n", report.RootStructOptSize))
			sb.WriteString(fmt.Sprintf("| 📈 优化率 | **%.1f%%** |\n", optRate))
		}
	}
	sb.WriteString("\n")

	// 分类结构体
	var optimized, skipped, unchanged []*optimizer.StructReport
	for _, sr := range report.StructReports {
		if sr.Skipped {
			skipped = append(skipped, sr)
		} else if sr.Saved > 0 {
			optimized = append(optimized, sr)
		} else {
			unchanged = append(unchanged, sr)
		}
	}

	// 2. 调整的结构体（优先显示）
	if len(optimized) > 0 {
		sb.WriteString("## ✏️ 调整的结构体\n\n")
		sb.WriteString(fmt.Sprintf("**共 %d 个结构体被优化**\n\n", len(optimized)))

		for _, sr := range optimized {
			warning := ""
			if sr.HasEmbed {
				warning = " ⚠️"
			}
			sb.WriteString(fmt.Sprintf("### 📦 %s.%s%s\n\n", sr.PkgPath, sr.Name, warning))
			sb.WriteString(fmt.Sprintf("**📁 文件**: `%s`\n\n", sr.File))
			if sr.HasEmbed {
				sb.WriteString("> ⚠️  **警告：包含匿名字段，优化后可能影响兼容性，请手动检查！**\n\n")
			}

			// 大小对比
			sb.WriteString("### 📏 内存优化\n\n")
			sb.WriteString("```\n")
			sb.WriteString(fmt.Sprintf("优化前：%6d 字节\n", sr.OrigSize))
			sb.WriteString(fmt.Sprintf("         ↓\n"))
			sb.WriteString(fmt.Sprintf("优化后：%6d 字节\n", sr.OptSize))
			sb.WriteString(fmt.Sprintf("         ↓\n"))
			sb.WriteString(fmt.Sprintf("节省：  %6d 字节 (%.1f%%)\n", sr.Saved, float64(sr.Saved)/float64(sr.OrigSize)*100))
			sb.WriteString("```\n\n")

			// 字段对比表格（同一行显示优化前后，包含大小和匿名标记）
			sb.WriteString("**字段顺序对比:**\n\n")
			sb.WriteString("| 序号 | 优化前 | 优化后 | 大小 | 变化 |\n")
			sb.WriteString("|:----:|--------|--------|------|------|\n")

			maxLen := len(sr.OrigFields)
			if len(sr.OptFields) > maxLen {
				maxLen = len(sr.OptFields)
			}

			for i := 0; i < maxLen; i++ {
				orig := "-"
				opt := "-"
				size := ""
				change := ""

				if i < len(sr.OrigFields) {
					orig = sr.OrigFields[i]
					if sr.FieldTypes != nil {
						if t, ok := sr.FieldTypes[orig]; ok {
							size = fmt.Sprintf("%d", getFieldSize(t))
							// 标记匿名字段
							if orig == t {
								orig = orig + " *(匿名)*"
							}
						}
					}
				}
				if i < len(sr.OptFields) {
					opt = sr.OptFields[i]
					// 优化后也检查是否匿名
					if sr.FieldTypes != nil {
						if t, ok := sr.FieldTypes[opt]; ok {
							if opt == t && !strings.Contains(opt, "(匿名)") {
								opt = opt + " *(匿名)*"
							}
						}
					}
				}
				if orig != "-" && opt != "-" && orig != opt {
					change = "🔄"
				}

				sb.WriteString(fmt.Sprintf("| %d | `%s` | `%s` | %s | %s |\n", i+1, orig, opt, size, change))
			}
			sb.WriteString("\n\n---\n\n")
		}
	}

	// 3. 异常跳过的结构体
	if len(skipped) > 0 {
		sb.WriteString("## ⚠️ 异常跳过的结构体\n\n")
		sb.WriteString(fmt.Sprintf("**共 %d 个结构体因异常被跳过**\n\n", len(skipped)))

		for _, sr := range skipped {
			sb.WriteString(fmt.Sprintf("### ⏭️ %s.%s\n\n", sr.PkgPath, sr.Name))
			sb.WriteString(fmt.Sprintf("**原因**: %s\n\n", sr.SkipReason))
		}
	}

	// 4. 未变化的结构体（详细模式下显示）
	if r.level >= ReportLevelFull && len(unchanged) > 0 {
		sb.WriteString("## ✔️ 未变化的结构体\n\n")
		sb.WriteString(fmt.Sprintf("**共 %d 个结构体无需优化**\n\n", len(unchanged)))

		sb.WriteString("| 结构体名 | 包路径 | 大小 |\n")
		sb.WriteString("|----------|--------|------|\n")
		for _, sr := range unchanged {
			sb.WriteString(fmt.Sprintf("| `%s` | `%s` | %d 字节 |\n", sr.Name, sr.PkgPath, sr.OrigSize))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n*Generated by StructOptimizer*\n")

	return sb.String(), nil
}
