package reporter

// Version information
const Version = "1.8.9"

// Lang represents a supported language
type Lang string

const (
	LangZH Lang = "zh" // Chinese (default)
	LangEN Lang = "en" // English
)

// i18n holds all translatable strings
type i18n struct {
	// Report header
	ReportTitle      string
	GeneratedTime    string
	VersionLabel     string

	// Overview section
	OverviewTitle        string
	TotalStructs         string
	OptimizedStructs     string
	SkippedStructs       string
	MemorySaved          string
	TotalSizeBefore      string
	TotalSizeAfter       string
	TotalOptRate         string
	RootStruct           string
	RootSizeBefore       string
	RootSizeAfter        string
	RootOptRate          string
	Bytes                string

	// Adjusted structs section
	AdjustedTitle     string
	AdjustedSummary   string
	FileLabel         string
	MemoryOptTitle    string
	BeforeLabel       string
	AfterLabel        string
	SavedLabel        string
	FieldCompareTitle string

	// Table headers
	ColNo          string
	ColBeforeName  string
	ColBeforeType  string
	ColSize        string
	ColAfterName   string
	ColAfterType   string
	ColChange      string

	// Skipped structs section
	SkippedNormalTitle   string
	SkippedNormalSummary string
	ReasonLabel          string

	// Error skipped section
	SkippedErrorTitle   string
	SkippedErrorSummary string

	// Unchanged section
	UnchangedTitle       string
	UnchangedSummary     string
	ColStructName        string
	ColPkgPath           string

	// Footer
	ReportEnd     string
	GenBy         string

	// Skip reasons (these appear in optimizer output, also used for classification)
	SkipReasonEmpty      string
	SkipReasonSingleField string
	SkipReasonByMethod   string
	SkipReasonByName     string
}

// zhStrings is the Chinese language strings
var zhStrings = i18n{
	ReportTitle:      "🚀 StructOptimizer 优化报告",
	GeneratedTime:    "🕐 生成时间",
	VersionLabel:     "📦 版本",

	OverviewTitle:        "📊 优化总览",
	TotalStructs:         "🔹 处理结构体总数",
	OptimizedStructs:     "✅ 优化的结构体",
	SkippedStructs:       "⏭️ 跳过的结构体",
	MemorySaved:          "💾 节省内存",
	TotalSizeBefore:      "📈 总优化前大小",
	TotalSizeAfter:       "📉 总优化后大小",
	TotalOptRate:         "📊 总优化率",
	RootStruct:           "🎯 主结构体",
	RootSizeBefore:       "📏 优化前大小",
	RootSizeAfter:        "📏 优化后大小",
	RootOptRate:          "📈 优化率",
	Bytes:                "字节",

	AdjustedTitle:     "✏️ 调整的结构体",
	AdjustedSummary:   "共 %d 个结构体被优化",
	FileLabel:         "📁 文件",
	MemoryOptTitle:    "📏 内存优化",
	BeforeLabel:       "优化前",
	AfterLabel:        "优化后",
	SavedLabel:        "节省",
	FieldCompareTitle: "字段顺序对比",

	ColNo:         "序号",
	ColBeforeName: "优化前 - 字段名",
	ColBeforeType: "优化前 - 类型",
	ColSize:       "大小",
	ColAfterName:  "优化后 - 字段名",
	ColAfterType:  "优化后 - 类型",
	ColChange:     "变化",

	SkippedNormalTitle:   "⏭️ 正常跳过的结构体",
	SkippedNormalSummary: "共 %d 个结构体被跳过",
	ReasonLabel:          "原因",

	SkippedErrorTitle:   "⚠️ 异常跳过的结构体",
	SkippedErrorSummary: "共 %d 个结构体因异常被跳过",

	UnchangedTitle:       "✔️ 未变化的结构体",
	UnchangedSummary:     "共 %d 个结构体无需优化",
	ColStructName:        "结构体名",
	ColPkgPath:           "包路径",

	ReportEnd:   "报告结束",
	GenBy:       "Generated by StructOptimizer",

	SkipReasonEmpty:       "空结构体",
	SkipReasonSingleField: "单字段结构体",
	SkipReasonByMethod:    "通过方法指定跳过",
	SkipReasonByName:      "通过名字指定跳过",
}

// enStrings is the English language strings
var enStrings = i18n{
	ReportTitle:      "🚀 StructOptimizer Optimization Report",
	GeneratedTime:    "🕐 Generated",
	VersionLabel:     "📦 Version",

	OverviewTitle:        "📊 Optimization Overview",
	TotalStructs:         "🔹 Total structs processed",
	OptimizedStructs:     "✅ Optimized structs",
	SkippedStructs:       "⏭️ Skipped structs",
	MemorySaved:          "💾 Memory saved",
	TotalSizeBefore:      "📈 Total size before",
	TotalSizeAfter:       "📉 Total size after",
	TotalOptRate:         "📊 Total optimization rate",
	RootStruct:           "🎯 Root struct",
	RootSizeBefore:       "📏 Size before",
	RootSizeAfter:        "📏 Size after",
	RootOptRate:          "📈 Optimization rate",
	Bytes:                "bytes",

	AdjustedTitle:     "✏️ Adjusted structs",
	AdjustedSummary:   "%d struct(s) optimized",
	FileLabel:         "📁 File",
	MemoryOptTitle:    "📏 Memory optimization",
	BeforeLabel:       "Before",
	AfterLabel:        "After",
	SavedLabel:        "Saved",
	FieldCompareTitle: "Field order comparison",

	ColNo:         "No.",
	ColBeforeName: "Before - Field",
	ColBeforeType: "Before - Type",
	ColSize:       "Size",
	ColAfterName:  "After - Field",
	ColAfterType:  "After - Type",
	ColChange:     "Change",

	SkippedNormalTitle:   "⏭️ Normal skipped structs",
	SkippedNormalSummary: "%d struct(s) skipped",
	ReasonLabel:          "Reason",

	SkippedErrorTitle:   "⚠️ Error skipped structs",
	SkippedErrorSummary: "%d struct(s) skipped due to errors",

	UnchangedTitle:       "✔️ Unchanged structs",
	UnchangedSummary:     "%d struct(s) require no optimization",
	ColStructName:        "Struct name",
	ColPkgPath:           "Package path",

	ReportEnd:   "End of report",
	GenBy:       "Generated by StructOptimizer",

	SkipReasonEmpty:       "Empty struct",
	SkipReasonSingleField: "Single-field struct",
	SkipReasonByMethod:    "Skipped by method",
	SkipReasonByName:      "Skipped by name",
}

// getStrings returns the i18n strings for the given language
func getStrings(lang Lang) i18n {
	switch lang {
	case LangEN:
		return enStrings
	default:
		return zhStrings
	}
}
